version: '3' #version de docker-compose

services:

  mariadb:
    build:
      context: ./requirements/mariadb #path to a directory containing a dockerfile
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    restart: always #la norme pour un server web a priori
  
  
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    links:
      - mariadb
    restart: always
  
  
  nginx:
    build:
      context: ./requirements/nginx
    env_file: .env
    restart: always

volumes:
  wp:
    name: wp
    driver_opts: 
      device: ${WP_HOST_VOLUME_PATH}
  db:
    name: db
    driver_opts: 
      device: ${MARIADB_HOST_VOLUME_PATH}  

    

    