version: '3'

services:

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    image: nginx
    working_dir: /var/www/html
    ports: 
      - 443:443
    volumes:
      - wp_data:/var/www/html
    networks: 
      - inception_network
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    image: wordpress
    working_dir: /var/www/html
    ports:
      - 9000:9000
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    restart: on-failure

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cassassi/data/wp_data
      o: bind 
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cassassi/data/db_data
      o: bind

networks:
  inception_network:
    driver: bridge